# Generated by Django 2.2 on 2019-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('participantes', models.ManyToManyField(to='business.Persona')),
            ],
        ),
    ]
