# Generated by Django 2.2 on 2019-07-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('projects', '0003_remove_project_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
