# Generated by Django 2.2 on 2019-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('projects', '0004_project_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participantes',
        ),
        migrations.AddField(
            model_name='project',
            name='participantes',
            field=models.ManyToManyField(to='persona.Persona'),
        ),
    ]
