# Generated by Django 2.2 on 2019-07-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190709_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
