# Generated by Django 2.2 on 2019-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20190715_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, to='tasks.Resource'),
        ),
    ]
