# Generated by Django 2.2 on 2019-07-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_participantes'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='proyectos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
