# Generated by Django 2.2 on 2019-07-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('business', '0002_empresa_proyectos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='empresa',
            name='miembros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
